#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: AssemblyFileVersion
    type: string
    default: $(AssemblyFileVersion)
  
  - name: Configuration
    type: string
    default: '$(Configuration)'

steps:
  - task: DownloadSecureFile@1
    displayName: 'Download Key Pair'
    inputs:
      secureFile: netfxKeypair.snk
      retryCount: 5
  - task: MSBuild@1
    displayName: 'BuildAllConfigurations using build.proj'
    inputs:
      solution: '**/build.proj'
      configuration: '${{parameters.Configuration }}'  
      msbuildArguments: '/p:AssemblyFileVersion=${{parameters.AssemblyFileVersion }} /t:BuildAllConfigurations /p:GenerateNuget=false /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(Agent.TempDirectory)\netfxKeypair.snk'
