#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: $(Year:YY)$(DayOfYear)$(Rev:.rr)
trigger:
  branches:
    include:
    - internal/release/4.0
  paths:
    include:
    - src
    - eng
    - tools
    - .config
    - build.proj
    - '*.cmd'
    - '*.sh'

schedules:
- cron: '30 4 * * Sun'
  displayName: Weekly Saturday 9:30 PM (UTC - 7) Build
  branches:
    include:
    - internal/release/4.0
  always: true

- cron: '30 5 * * Mon-Fri'
  displayName: Mon-Fri 10:30 PM (UTC - 7) Build
  branches:
    include:
    - internal/release/4.0

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false
- name: oneBranchType
  displayName: 'Select OneBranch template'
  default: Official
  values:
  - NonOfficial
  - Official
- name: publishSymbols
  type: boolean
  default: false
- name: MDS_PackageRef_Version
  displayName: 'MDS package version of AKV Provider (build AKV)'
  type: string
  default: 3.0.0
- name: CurrentNetFxVersion
  displayName: 'Lowest supported .NET Framework version (MDS validation)'
  type: string
  default: 'net461'

variables:
  - template: /eng/pipelines/libraries/variables.yml@self
  - name: packageFolderName
    value: drop_buildMDS_build_signed_package
  - name: PublishSymbols
    value: ${{ parameters['publishSymbols'] }}
  - name: MDS_PackageRef_Version
    value: ${{ parameters['MDS_PackageRef_Version'] }}
  - name: CurrentNetFxVersion
    value: ${{ parameters['CurrentNetFxVersion'] }}
  - name: ProductVersion    #MDS product version (MDS validation)
    value: $(NUGETPACKAGEVERSION)

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.${{ parameters['oneBranchType'] }}.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    globalSdl: # https://aka.ms/obpipelines/sdl
      apiscan:
        enabled: true
        softwareFolder: $(softwareFolder)
        symbolsFolder: $(symbolsFolder)
        softwarename: Microsoft.Data.SqlClient
        versionNumber: $(AssemblyFileVersion)
      tsa:
        enabled: true # onebranch publish all sdl results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      codeql:
        compiled:
          enabled: false #[warning]Consider running CodeQL on the default branch only.
      sbom:
        enabled: true
        packageName: Microsoft.Data.SqlClient
        packageVersion: $(NugetPackageVersion)
      policheck:
        enabled: true
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
        exclusionsFile: $(REPOROOT)\.config\PolicheckExclusions.xml
      asyncSdl:
        enabled: false
        credscan:
          enabled: true
          suppressionsFile: $(REPOROOT)/.config/CredScanSuppressions.json
        binskim:
          enabled: true
        armory:
          enabled: true
          break: true
        eslint: # TypeScript and JavaScript
          enabled: false
        roslyn:
          enabled: true
          break: true
        publishLogs:
          enabled: true
        tsaOptionsPath: $(REPOROOT)\.config\tsaoptions.json
        disableLegacyManifest: true
    stages:
    - stage: buildAKV
      jobs:
      - template: eng/pipelines/common/templates/jobs/build-signed-akv-package-job.yml@self
        parameters:
          symbolsFolder: $(symbolsFolder)
          softwareFolder: $(softwareFolder)
          publishSymbols: ${{ parameters['publishSymbols'] }}

    - stage: buildMDS
      jobs:
      - template: eng/pipelines/common/templates/jobs/build-signed-package-job.yml@self
        parameters:
          symbolsFolder: $(symbolsFolder)
          softwareFolder: $(softwareFolder)
          publishSymbols: ${{ parameters['publishSymbols'] }}

    - stage: package_validation
      dependsOn: buildMDS
      jobs:
      - template: eng/pipelines/common/templates/jobs/validate-signed-package-job.yml@self
        parameters:
          packageFolderName: $(packageFolderName)
          downloadPackageStep:
            download: current
            artifact: $(packageFolderName)
            patterns: '**/*.nupkg'
            displayName: 'Download NuGet Package'

      - template: eng/pipelines/common/templates/jobs/run-tests-package-reference-job.yml@self
        parameters:
          packageFolderName: $(packageFolderName)
          downloadPackageStep:
            download: current
            artifact: $(packageFolderName)
            patterns: '**/*.nupkg'
            displayName: 'Download NuGet Package'
