name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: nuget/setup-nuget@v1
      - name: rename
        shell: powershell
        run: |
          $file = Get-Item tools/specs/Microsoft.Data.SqlClient.nuspec
          $spec = [xml] (Get-Content $file.FullName)
          $spec.package.metadata.id = 'Rabota.Data.SqlClient'
          $spec.package.metadata.title = 'Rabota.Data.SqlClient'
          $spec.Save($file.FullName)
      - run: msbuild /t:BuildAllConfigurations /p:Configuration=Release /p:NugetPackageVersion=3.0.0-mac
      - run: mv packages/Microsoft.Data.SqlClient.3.0.0-mac.nupkg packages/Rabota.Data.SqlClient.3.0.0-mac.nupkg
      - run: dir packages
      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: packages/*.nupkg