name: Microservice Workflow
on:
  pull_request:
    types:
      - closed
    branches: [main]
env:
  LEANIX_API_TOKEN: "wm6X3aYuJX4ZLKpOufgDz5zt8LVAucGcL77WALL6"
  LEANIX_SUBDOMAIN: "leanix"

jobs:
  update_microservice:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: ${{ github.repositoryUrl }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      - name: Invoke Manifest Parser
        run: python leanix_service_discovery.py
